sudo: required
services:
  - docker
language: c

environment:
  # We test only CPU kernels on Travis.  Sad face.
  - DOCKER_IMG=tensorflow/tensorflow:nightly-devel-py3
  - DOCKER_IMG=tensorflow/tensorflow:latest-devel-py3
  - DOCKER_IMG=tensorflow/tensorflow:1.2.1-devel-py3
  - DOCKER_IMG=tensorflow/tensorflow:1.2.0-devel-py3
  - DOCKER_IMG=tensorflow/tensorflow:1.1.0-devel-py3

before_install:
  - docker pull $DOCKER_IMG

script:
  - docker run -e NO_GPU=1 -ti -v $(pwd):/src -w /src $DOCKER_IMG ./run_tests.sh
